#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of the ZObject project
#
# 
#
# Distributed under the terms of the GPL license.
# See LICENSE.txt for more info.

try:
    from ZObject import main
except ImportError:
    import os, sys
    __this_dir = os.path.dirname(os.path.abspath(__file__))
    __package_dir = os.path.join(__this_dir, os.path.pardir)
    sys.path.append(__package_dir)
    from ZObject import main

if __name__ == "__main__":
    main()
